name: Docker Image CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image
      run: |
        IMAGE_NAME=$(uuidgen)
        docker build -t ttl.sh/${IMAGE_NAME}:24h .
        docker push ttl.sh/${IMAGE_NAME}:24h
        echo "Image ttl.sh/${IMAGE_NAME}:24h is available for 24 hours"
